<?php
/**
 * Auto-generated PostgreSQL DDL for legacy tables that have no CREATE site in
 * the application (they were created manually in the original MySQL database).
 * Source of truth: the migrated Neon schema. Regenerate with gb_gen_legacy.php.
 */

function ensure_legacy_tables(PDO $pdo): void
{

    $pdo->exec("CREATE TABLE IF NOT EXISTS company_invitations (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        business_id INTEGER NOT NULL,
        invited_by_user_id INTEGER NOT NULL,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        phone VARCHAR(50),
        role TEXT NOT NULL DEFAULT 'worker'::text,
        token_hash VARCHAR(255) NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending'::text,
        expires_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        accepted_user_id INTEGER,
        accepted_at TIMESTAMP,
        created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT fk_company_invitations_company_invitations_ibfk_1 FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_company_invitations_company_invitations_ibfk_2 FOREIGN KEY (invited_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_company_invitations_company_invitations_ibfk_3 FOREIGN KEY (accepted_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE
    );");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_company_invitations_accepted_user_id ON company_invitations USING btree (accepted_user_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_company_invitations_invitation_email_status ON company_invitations USING btree (business_id, email, status)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_company_invitations_invitation_token_status ON company_invitations USING btree (token_hash, status)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_company_invitations_invited_by_user_id ON company_invitations USING btree (invited_by_user_id)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS enterprise_accounts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR(255) NOT NULL,
        slug VARCHAR(100) NOT NULL,
        contact_email VARCHAR(255),
        contact_phone VARCHAR(50),
        branding_primary_color VARCHAR(7) DEFAULT '#0d6efd'::character varying,
        branding_logo_url VARCHAR(500),
        status TEXT NOT NULL DEFAULT 'pending'::text,
        created_by_user_id INTEGER,
        created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT uq_enterprise_accounts_slug UNIQUE (slug),
        CONSTRAINT fk_enterprise_accounts_enterprise_accounts_ibfk_1 FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE
    );");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_enterprise_accounts_created_by_user_id ON enterprise_accounts USING btree (created_by_user_id)");
    $pdo->exec("CREATE UNIQUE INDEX IF NOT EXISTS uq_enterprise_accounts_slug ON enterprise_accounts USING btree (slug)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS enterprise_members (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        enterprise_account_id INTEGER NOT NULL,
        business_id INTEGER NOT NULL,
        role TEXT NOT NULL DEFAULT 'member'::text,
        invited_by_user_id INTEGER,
        joined_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT uq_enterprise_members_enterprise_business UNIQUE (enterprise_account_id, business_id),
        CONSTRAINT fk_enterprise_members_enterprise_members_ibfk_1 FOREIGN KEY (enterprise_account_id) REFERENCES enterprise_accounts(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_enterprise_members_enterprise_members_ibfk_2 FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_enterprise_members_enterprise_members_ibfk_3 FOREIGN KEY (invited_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE
    );");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_enterprise_members_business_id ON enterprise_members USING btree (business_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_enterprise_members_invited_by_user_id ON enterprise_members USING btree (invited_by_user_id)");
    $pdo->exec("CREATE UNIQUE INDEX IF NOT EXISTS uq_enterprise_members_enterprise_business ON enterprise_members USING btree (enterprise_account_id, business_id)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS manager_grants (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        business_id INTEGER NOT NULL,
        user_id INTEGER NOT NULL,
        granted_by_user_id INTEGER NOT NULL,
        granted_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        expires_at TIMESTAMP,
        revoked_at TIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT fk_manager_grants_manager_grants_ibfk_1 FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_manager_grants_manager_grants_ibfk_2 FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_manager_grants_manager_grants_ibfk_3 FOREIGN KEY (granted_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE
    );");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_manager_grants_granted_by_user_id ON manager_grants USING btree (granted_by_user_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_manager_grants_manager_grants_scope ON manager_grants USING btree (business_id, user_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_manager_grants_user_id ON manager_grants USING btree (user_id)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS monthly_billings (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        business_id INTEGER NOT NULL,
        billing_month VARCHAR(7) NOT NULL,
        billing_start_date DATE NOT NULL,
        billing_end_date DATE NOT NULL,
        due_date DATE NOT NULL,
        payment_status TEXT NOT NULL DEFAULT 'pending'::text,
        settlement_reference_number VARCHAR(100) NOT NULL,
        invoice_number VARCHAR(100),
        total_monthly_revenue NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        referral_commissions NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        platform_fees NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        settled_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        unpaid_balance NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        carry_forward_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        conversion_rate NUMERIC(5,2) NOT NULL DEFAULT 0.00,
        locked_at TIMESTAMP,
        archived_at TIMESTAMP,
        generated_at TIMESTAMP,
        created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT uq_monthly_billings_monthly_billing_reference UNIQUE (settlement_reference_number),
        CONSTRAINT uq_monthly_billings_monthly_billing_scope UNIQUE (business_id, billing_month),
        CONSTRAINT fk_monthly_billings_monthly_billings_ibfk_1 FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE
    );");
    $pdo->exec("CREATE UNIQUE INDEX IF NOT EXISTS uq_monthly_billings_monthly_billing_reference ON monthly_billings USING btree (settlement_reference_number)");
    $pdo->exec("CREATE UNIQUE INDEX IF NOT EXISTS uq_monthly_billings_monthly_billing_scope ON monthly_billings USING btree (business_id, billing_month)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS outstanding_balances (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        billing_id INTEGER NOT NULL,
        business_id INTEGER NOT NULL,
        balance_type TEXT NOT NULL,
        amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        remaining_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        due_date DATE NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending'::text,
        created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT uq_outstanding_balances_outstanding_balance_scope UNIQUE (billing_id, balance_type),
        CONSTRAINT fk_outstanding_balances_outstanding_balances_ibfk_1 FOREIGN KEY (billing_id) REFERENCES monthly_billings(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_outstanding_balances_outstanding_balances_ibfk_2 FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE
    );");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_outstanding_balances_business_id ON outstanding_balances USING btree (business_id)");
    $pdo->exec("CREATE UNIQUE INDEX IF NOT EXISTS uq_outstanding_balances_outstanding_balance_scope ON outstanding_balances USING btree (billing_id, balance_type)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS platform_commissions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        billing_id INTEGER NOT NULL,
        business_id INTEGER NOT NULL,
        referral_id INTEGER,
        fee_type TEXT NOT NULL DEFAULT 'percentage'::text,
        commission_percentage NUMERIC(5,2) NOT NULL DEFAULT 0.00,
        fixed_fee NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        gross_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        platform_fee NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        status TEXT NOT NULL DEFAULT 'pending_settlement'::text,
        created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT uq_platform_commissions_platform_commission_referral UNIQUE (referral_id),
        CONSTRAINT fk_platform_commissions_platform_commissions_ibfk_1 FOREIGN KEY (billing_id) REFERENCES monthly_billings(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_platform_commissions_platform_commissions_ibfk_2 FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_platform_commissions_platform_commissions_ibfk_3 FOREIGN KEY (referral_id) REFERENCES referrals(id) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE
    );");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_platform_commissions_billing_id ON platform_commissions USING btree (billing_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_platform_commissions_business_id ON platform_commissions USING btree (business_id)");
    $pdo->exec("CREATE UNIQUE INDEX IF NOT EXISTS uq_platform_commissions_platform_commission_referral ON platform_commissions USING btree (referral_id)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS pms_integrations (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        enterprise_account_id INTEGER,
        business_id INTEGER,
        integration_type TEXT NOT NULL DEFAULT 'pms'::text,
        provider_name VARCHAR(100) NOT NULL,
        provider_code VARCHAR(50) NOT NULL,
        status TEXT NOT NULL DEFAULT 'none'::text,
        api_endpoint VARCHAR(500),
        api_key_hint VARCHAR(100),
        webhook_secret_hint VARCHAR(100),
        last_sync_at TIMESTAMP,
        sync_status TEXT,
        config_json TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT fk_pms_integrations_pms_integrations_ibfk_1 FOREIGN KEY (enterprise_account_id) REFERENCES enterprise_accounts(id) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE,
        CONSTRAINT fk_pms_integrations_pms_integrations_ibfk_2 FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE
    );");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_pms_integrations_business_id ON pms_integrations USING btree (business_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_pms_integrations_enterprise_account_id ON pms_integrations USING btree (enterprise_account_id)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS role_permissions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        role_name VARCHAR(50) NOT NULL,
        permission_key VARCHAR(100) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT uq_role_permissions_role_permission_unique UNIQUE (role_name, permission_key)
    );");
    $pdo->exec("CREATE UNIQUE INDEX IF NOT EXISTS uq_role_permissions_role_permission_unique ON role_permissions USING btree (role_name, permission_key)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS settlement_logs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        billing_id INTEGER,
        business_id INTEGER NOT NULL,
        user_id INTEGER,
        action TEXT NOT NULL,
        amount NUMERIC(12,2),
        note TEXT,
        old_value TEXT,
        new_value TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT fk_settlement_logs_settlement_logs_ibfk_1 FOREIGN KEY (billing_id) REFERENCES monthly_billings(id) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE,
        CONSTRAINT fk_settlement_logs_settlement_logs_ibfk_2 FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_settlement_logs_settlement_logs_ibfk_3 FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE
    );");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_settlement_logs_billing_id ON settlement_logs USING btree (billing_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_settlement_logs_business_id ON settlement_logs USING btree (business_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_settlement_logs_user_id ON settlement_logs USING btree (user_id)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS user_sessions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        user_id INTEGER NOT NULL,
        session_id VARCHAR(128) NOT NULL,
        ip_address VARCHAR(45),
        user_agent TEXT,
        last_active_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT fk_user_sessions_user_sessions_ibfk_1 FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE
    );");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_user_sessions_user_id ON user_sessions USING btree (user_id)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS billing_notifications (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        billing_id INTEGER NOT NULL,
        business_id INTEGER NOT NULL,
        notification_type TEXT NOT NULL,
        channel VARCHAR(50) NOT NULL DEFAULT 'dashboard'::character varying,
        message TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending'::text,
        created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        sent_at TIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT fk_billing_notifications_billing_notifications_ibfk_1 FOREIGN KEY (billing_id) REFERENCES monthly_billings(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_billing_notifications_billing_notifications_ibfk_2 FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE
    );");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_billing_notifications_billing_id ON billing_notifications USING btree (billing_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_billing_notifications_billing_notifications_scope ON billing_notifications USING btree (business_id, notification_type, status)");

    $pdo->exec("CREATE TABLE IF NOT EXISTS billing_transactions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        billing_id INTEGER NOT NULL,
        business_id INTEGER NOT NULL,
        referral_id INTEGER,
        commission_id INTEGER,
        transaction_type TEXT NOT NULL,
        description VARCHAR(255),
        gross_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        platform_fee NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        commission_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        business_earnings NUMERIC(12,2) NOT NULL DEFAULT 0.00,
        status TEXT NOT NULL DEFAULT 'pending_settlement'::text,
        occurred_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT fk_billing_transactions_billing_transactions_ibfk_1 FOREIGN KEY (billing_id) REFERENCES monthly_billings(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_billing_transactions_billing_transactions_ibfk_2 FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE RESTRICT ON DELETE CASCADE DEFERRABLE,
        CONSTRAINT fk_billing_transactions_billing_transactions_ibfk_3 FOREIGN KEY (referral_id) REFERENCES referrals(id) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE,
        CONSTRAINT fk_billing_transactions_billing_transactions_ibfk_4 FOREIGN KEY (commission_id) REFERENCES commissions(id) ON UPDATE RESTRICT ON DELETE SET NULL DEFERRABLE
    );");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_billing_transactions_billing_id ON billing_transactions USING btree (billing_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_billing_transactions_billing_transactions_month ON billing_transactions USING btree (business_id, billing_id, status)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_billing_transactions_commission_id ON billing_transactions USING btree (commission_id)");
    $pdo->exec("CREATE INDEX IF NOT EXISTS ix_billing_transactions_referral_id ON billing_transactions USING btree (referral_id)");
}


/**
 * Columns that were added manually to the original MySQL database and are not
 * part of any CREATE TABLE in the application code. Auto-generated from the
 * migrated PostgreSQL schema (see gb_gen_cols.php).
 */
function ensure_legacy_columns(PDO $pdo): void
{
    $table_ready = $pdo->prepare('SELECT to_regclass(?) IS NOT NULL');
    $col_exists = $pdo->prepare('SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ? AND column_name = ?');
    $adds = [
        ['businesses', 'logo_url', 'VARCHAR(500)'],
        ['businesses', 'momo_number', 'VARCHAR(50)'],
        ['businesses', 'bank_name', 'VARCHAR(255)'],
        ['businesses', 'bank_account', 'VARCHAR(100)'],
        ['businesses', 'bank_swift', 'VARCHAR(20)'],
        ['businesses', 'paypal_email', 'VARCHAR(255)'],
        ['businesses', 'currency', 'VARCHAR(10) NOT NULL DEFAULT \'USD\'::character varying'],
        ['businesses', 'referral_code', 'VARCHAR(555)'],
        ['businesses', 'platform_fee_type', 'TEXT NOT NULL DEFAULT \'percentage\'::text'],
        ['businesses', 'platform_commission_percentage', 'NUMERIC(5,2)'],
        ['businesses', 'fixed_monthly_subscription_fee', 'NUMERIC(10,2)'],
        ['commissions', 'settlement_status', 'TEXT NOT NULL DEFAULT \'pending_settlement\'::text'],
        ['commissions', 'billing_id', 'INTEGER'],
        ['invoices', 'billing_id', 'INTEGER'],
        ['invoices', 'billing_month', 'VARCHAR(7)'],
        ['invoices', 'total_revenue', 'NUMERIC(12,2) NOT NULL DEFAULT 0.00'],
        ['invoices', 'platform_fees', 'NUMERIC(12,2) NOT NULL DEFAULT 0.00'],
        ['invoices', 'referral_commissions', 'NUMERIC(12,2) NOT NULL DEFAULT 0.00'],
        ['invoices', 'settled_amount', 'NUMERIC(12,2) NOT NULL DEFAULT 0.00'],
        ['invoices', 'unpaid_balance', 'NUMERIC(12,2) NOT NULL DEFAULT 0.00'],
        ['login_history', 'country', 'VARCHAR(100)'],
        ['login_history', 'city', 'VARCHAR(100)'],
        ['pilot_notifications', 'trigger_type', 'TEXT NOT NULL DEFAULT \'readiness_75\'::text'],
        ['pilot_notifications', 'readiness_score', 'INTEGER NOT NULL DEFAULT 0'],
        ['pilot_notifications', 'triggered_by_user_id', 'INTEGER'],
        ['pilot_notifications', 'reviewed_by_user_id', 'INTEGER'],
        ['pilot_notifications', 'reviewed_at', 'TIMESTAMP'],
        ['platform_config', 'config_key', 'VARCHAR(100) NOT NULL'],
        ['platform_config', 'config_value', 'TEXT NOT NULL'],
        ['platform_config', 'updated_at', 'TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP'],
        ['referral_redemptions', 'transaction_amount', 'NUMERIC(12,2)'],
        ['referral_redemptions', 'receipt_path', 'VARCHAR(500)'],
        ['referral_redemptions', 'commission_calculated', 'TEXT'],
        ['referrals', 'amount_consumed', 'NUMERIC(10,2) NOT NULL DEFAULT 0.00'],
        ['referrals', 'estimated_fee', 'NUMERIC(10,2) NOT NULL DEFAULT 0.00'],
        ['referrals', 'estimated_platform_fee', 'NUMERIC(10,2) NOT NULL DEFAULT 0.00'],
        ['referrals', 'estimated_business_earnings', 'NUMERIC(10,2) NOT NULL DEFAULT 0.00'],
        ['referrals', 'settlement_status', 'TEXT NOT NULL DEFAULT \'pending_settlement\'::text'],
        ['referrals', 'consumed_at', 'TIMESTAMP'],
        ['referrals', 'consumed_by', 'INTEGER'],
        ['referrals', 'consumption_notes', 'TEXT'],
        ['referrals', 'service_category', 'VARCHAR(120)'],
        ['referrals', 'billing_id', 'INTEGER'],
        ['referrals', 'billing_month', 'VARCHAR(7)'],
        ['staff', 'status', 'TEXT NOT NULL DEFAULT \'active\'::text'],
        ['users', 'two_factor_enabled', 'SMALLINT NOT NULL DEFAULT 0'],
        ['users', 'status', 'TEXT NOT NULL DEFAULT \'active\'::text'],
        ['users', 'email_verified_at', 'TIMESTAMP'],
        ['users', 'email_verification_token', 'VARCHAR(128)'],
        ['users', 'phone_verified_at', 'TIMESTAMP'],
        ['users', 'phone_verification_token', 'VARCHAR(32)'],
        ['users', 'invited_by_user_id', 'INTEGER'],
        ['users', 'last_login_at', 'TIMESTAMP'],
        ['users', 'is_deleted', 'SMALLINT NOT NULL DEFAULT 0'],
    ];
    foreach ($adds as [$table, $name, $def]) {
        $table_ready->execute([$table]);
        if (!$table_ready->fetchColumn()) {
            continue;
        }
        $col_exists->execute([$table, $name]);
        if ($col_exists->fetchColumn()) {
            continue;
        }
        $pdo->exec('ALTER TABLE ' . $table . ' ADD COLUMN ' . $name . ' ' . $def);
    }
}
